# Generated by Django 4.2.16 on 2024-09-23 23:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('segundo_nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('segundo_apellido', models.CharField(max_length=50)),
                ('tipo_documento', models.CharField(choices=[('CC', 'Cédula de Ciudadanía'), ('TI', 'Tarjeta de Identidad'), ('CE', 'Cédula de Extranjería'), ('PA', 'Pasaporte')], max_length=2)),
                ('fecha_nacimiento', models.DateField()),
                ('genero', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro')], max_length=1)),
                ('telefono', models.PositiveIntegerField()),
                ('direccion', models.CharField(max_length=50)),
                ('direccion_facturacion', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Vuelos',
            fields=[
                ('id_vuelo', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('ciudad_origen', models.CharField(max_length=25)),
                ('ciudad_destino', models.CharField(max_length=25)),
                ('precio', models.PositiveIntegerField()),
                ('fecha_salida', models.DateTimeField()),
                ('fecha_llegada', models.DateTimeField()),
                ('tipo', models.CharField(choices=[('N', 'Nacional'), ('I', 'Internacional')], max_length=20)),
                ('estado', models.CharField(choices=[('P', 'Programado'), ('R', 'Realizado'), ('C', 'Cancelado')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='NormalUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('user_id', models.PositiveBigIntegerField(unique=True)),
                ('email', models.EmailField(max_length=100, unique=True, verbose_name='direccion de correo electrónico')),
                ('roles', models.PositiveSmallIntegerField(choices=[(1, 'Cliente'), (2, 'Administrador'), (3, 'Root')])),
                ('activo', models.BooleanField(default=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Tiquete',
            fields=[
                ('id_tiquete', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('clase', models.CharField(choices=[('E', 'Clase económica'), ('P', 'Primera clase')], max_length=20)),
                ('tipo_equipaje', models.CharField(choices=[('EP', 'Equipaje personal'), ('EM', 'Equipaje de mano'), ('MB', 'Maleta de bodega')], max_length=20)),
                ('verificacion', models.CharField(max_length=50, unique=True)),
                ('id_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WingCol.cliente')),
                ('id_vuelo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WingCol.vuelos')),
            ],
        ),
        migrations.CreateModel(
            name='Tarjetas',
            fields=[
                ('id_tarjeta', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('tipo_tarjeta', models.CharField(choices=[('D', 'Débito'), ('C', 'Crédito')], max_length=20)),
                ('vvc', models.PositiveIntegerField()),
                ('fecha_expiracion', models.DateField()),
                ('saldo', models.IntegerField()),
                ('id_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WingCol.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Sillas',
            fields=[
                ('id_silla', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('ubicacion', models.CharField(max_length=5)),
                ('clase', models.CharField(choices=[('E', 'Clase económica'), ('P', 'Primera clase')], max_length=20)),
                ('estado', models.CharField(choices=[('L', 'Libre'), ('R', 'Reservado'), ('O', 'Ocupado')], max_length=20)),
                ('id_vuelo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WingCol.vuelos')),
            ],
        ),
        migrations.CreateModel(
            name='Root',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ComprasReservas',
            fields=[
                ('id_cr', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('estado', models.CharField(choices=[('COM', 'Comprado'), ('RES', 'Reservado'), ('CAN', 'Cancelado')], max_length=20)),
                ('valor', models.PositiveIntegerField()),
                ('id_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WingCol.cliente')),
                ('id_vuelo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WingCol.vuelos')),
            ],
        ),
        migrations.AddField(
            model_name='cliente',
            name='user_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Busquedas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ciudad_origen', models.CharField(max_length=25)),
                ('ciudad_destino', models.CharField(max_length=25)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('id_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WingCol.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='AdministraDor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('segundo_nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('segundo_apellido', models.CharField(max_length=50)),
                ('genero', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro')], max_length=1)),
                ('telefono', models.PositiveIntegerField()),
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
