# Generated by Django 4.2.16 on 2024-09-24 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WingCol', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='telefono',
            field=models.CharField(max_length=20),
        ),
    ]
