# Generated by Django 4.2.16 on 2024-09-26 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WingCol', '0002_alter_cliente_telefono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administrador',
            name='segundo_nombre',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='segundo_nombre',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
