# Generated by Django 4.2.16 on 2024-09-27 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WingCol', '0003_alter_administrador_segundo_nombre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='pais',
            field=models.CharField(default='Colombia', max_length=20),
        ),
    ]
