# Generated by Django 4.2.16 on 2024-09-27 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WingCol', '0004_cliente_pais'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='pais',
            field=models.CharField(max_length=20),
        ),
    ]
